server:
  port: 8081
  servlet.context-path: /sso-auth-server

security.oauth2.client:
  client-id: product-client
  client-secret: 27917C58F8435247CF2C5C9D0EDF64AE702C005ACFE242110CC9C4F0E7AF2758
  grant-type: code
  scope: read,write

### Only for academic purposes, these endpoints shouldn't be unsecured
security.oauth2.authorization.check-token-access: permitAll()
security.oauth2.authorization.token-key-access: permitAll()