server:
  port: 8081
  servlet.context-path: /sso-auth-server

security.oauth2.client:
  client-id: bael-client
  client-secret: bael-secret
  grant-type: code
  scope: read,write

### Only for academic purposes, these endpoints shouldn't be unsecured
security.oauth2.authorization.check-token-access: permitAll()
security.oauth2.authorization.token-key-access: permitAll()